### ISSUE TITLE
Exception thrown in AppCode

### ISSUE THREAD

**Issue by richardlalancetteyoui** [ArtsiomCh/CMake#16]
Application: AppCode
OS: Mac
Plugin: CMake simple Highlighter

Exception:
```java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:160)
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:153)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:75)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:27)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:970)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:952)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:157)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:144)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:144)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:144)
	at com.intellij.util.diff.DiffTree.diff(DiffTree.java:61)
	at com.intellij.psi.impl.BlockSupportImpl.diffTrees(BlockSupportImpl.java:342)
	at com.intellij.lang.impl.PsiBuilderImpl.merge(PsiBuilderImpl.java:994)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:908)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:899)
	at com.cmakeplugin.parsing.CMakeParser.parse(CMakeParser.java:20)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:245)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:365)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:311)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:244)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:104)
	at com.intellij.psi.impl.BlockSupportImpl.reparseRange(BlockSupportImpl.java:71)
	at com.intellij.codeInsight.completion.OffsetsInFile.reparseFile(OffsetsInFile.kt:66)
	at com.intellij.codeInsight.completion.OffsetsInFile.replaceInCopy(OffsetsInFile.kt:56)
	at com.intellij.codeInsight.completion.CompletionInitializationUtil.insertDummyIdentifier(CompletionInitializationUtil.java:133)
	at com.intellij.codeInsight.completion.CompletionInitializationUtil.prepareCompletionParameters(CompletionInitializationUtil.java:88)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.prepareCompletionParameters(CodeCompletionHandlerBase.java:305)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:270)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by ArtsiomCh** [comment]
Hi Richard! Thank you for the report and sorry for late response.
Unfortunately I have no access to PC with MacOS and AppCode doesn't have version for Linux/Windows OS.
Could you please send me more info about that exception:
Do you have it every time at Appcode or it happens time to time only?
What is the full exception description? I see you proved Stack Trace only but looks like the description is missed.
PS And by the way, does AppCode have any built CMake support? I.e. can you build projects using CMake and does AppCode have any built-in CMake highlighting?

**Comment by ArtsiomCh** [comment]
No response, hence the issue is obsolete.
