### ISSUE TITLE
Cmake Plus crashes on startup

### ISSUE THREAD

**Issue by geordyvc** [ArtsiomCh/CMake#24]
I have bought a license but I cannot activate it because the plugin keeps crashing on startup.

Clion version: 2020.3.2

Exception:
```
Plugin 'artsiomch.cmake.plus' failed to initialize and will be disabled. Please restart CLion.

java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\geordy.vancutsem\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\203.7148.70\jbr\bin\java.exe": CreateProcess error=5, Toegang geweigerd
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:94)
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:72)
    at com.cmakeplugin.agent.CMakeInstrumentationUtils.patchJBclasses(CMakeInstrumentationUtils.java:83)
    at com.cmakeplugin.CMakePlusComponent.initComponent(CMakePlusComponent.java:42)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:304)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:347)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:347)
    at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:200)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
    at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: Cannot run program "C:\Users\geordy.vancutsem\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\203.7148.70\jbr\bin\java.exe": CreateProcess error=5, Toegang geweigerd
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
    at org.avaje.agentloader.load.ExternalLoader.loadAgent(ExternalLoader.java:84)
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:88)
    ... 40 more
Caused by: java.io.IOException: CreateProcess error=5, Toegang geweigerd
    at java.base/java.lang.ProcessImpl.create(Native Method)
    at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
    at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
    ... 43 more
```

I also commented on an issue in the Youtrack from Jetbrains. 
https://youtrack.jetbrains.com/issue/IDEA-248513
This is not your problem but the activation of licenses should be more user-friendly.

**Comment by ArtsiomCh** [comment]
Thanks for reporting! 
Looks like the problem happened inside the third party library I'm using. Will investigate how that could be fixed.

**Comment by ArtsiomCh** [comment]
Unable to reproduce your issue.
Looking into stacktrace above I can see that for some reason the `java.exe` from JetBrains runtime can't start:
`Cannot run program "C:\Users\geordy.vancutsem\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\203.7148.70\jbr\bin\java.exe"` and the reason is `Toegang geweigerd` which is translated from Dutch as `access denied` (?)
Please check you didn't explicitly put any restriction for starting `...\CLion\ch-0\203.7148.70\jbr\bin\java.exe` or if any software on your PC (antivirus?) restrict it to start.

PS `idea.log` file might also help to investigate the issue: [Locating IDE log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by ArtsiomCh** [comment]
Presume issue is solved. If not - let me know please.
