### ISSUE TITLE
[Exception][CLion 2022.3 RC] java.lang.StackOverflowError

### ISSUE THREAD

**Issue by liuguilin361** [ArtsiomCh/CMake#40]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.StackOverflowError
	at com.cmakeplugin.docs.ParamNode.copy$default(ParamsTree.kt)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:485)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.ParamsTree.getNodes(ParamsTree.kt:534)
	at com.cmakeplugin.docs.Par

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: CLion 2022.3 RC Build: #CL-223.7571.113 November 23, 2022
Theme: Light
JRE: 17.0.5+1-b653.14, JetBrains s.r.o.
JVM: 17.0.5+1-b653.14, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11 10.0 (amd64)

=== Plugins ===
Custom plugins: [Rust (0.4.183.5026-223), Chinese (Simplified) Language Pack / 中文语言包 (223.143), PlatformIO for CLion (223.7571.113), CMake simple highlighter (223.1.0), Ini (223.7571.123)]
Disabled plugins:[CMake Plus (223.1.0), GN (0.1.3-10-gd0c87bc)]
```

**Comment by ArtsiomCh** [comment]
Hi @galenliu ! 
Thanks for submitting the issue! Could you please give me a bit more details about it:
1. Is it reproducible or you've seen it only once (or few times but no way to reproduce)?
2. If it's reproducible, could you provide me the piece of cmake code where you've observe the issue, please?

**Comment by ArtsiomCh** [comment]
Will close for now as it seems to be one time glitch.
If happens again, don't hesitate to write comment here with details.
And again Thank you for reporting!
