### ISSUE TITLE
[Exception][CLion 2022.3] In file: file:///<path to repo>/CMakeLists.txt

### ISSUE THREAD

**Issue by pzheltov** [ArtsiomCh/CMake#42]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.cmake.psi.CMakeCommandImpl #CMake  because: parent is null
invalidated at: see attachment
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:76)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:53)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:213)
	at com.cmakeplugin.utils.CMakePSITreeSearch.lambda$cleanCachesForDisposedProjects$5(CMakePSITreeSearch.java:71)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at com.cmakeplugin.utils.CMakePSITreeSearch.lambda$cleanCachesForDisposedProjects$7(CMakePSITreeSearch.java:71)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.cmakeplugin.utils.CMakePSITreeSearch.cleanCachesForDisposedProjects(CMakePSITreeSearch.java:66)
	at com.cmakeplugin.utils.CMakePSITreeSearch.addFileListener(CMakePSITreeSearch.java:59)
	at com.cmakeplugin.utils.CMakePSITreeSearch.getCmakeFiles(CMakePSITreeSearch.java:94)
	at com.cmakeplugin.utils.CMakePSITreeSearch.existCommandDefFor(CMakePSITreeSearch.java:318)
	at com.cmakeplugin.utils.CMakePSITreeSearch.existFunctionDefFor(CMakePSITreeSearch.java:298)
	at com.cmakeplugin.annotator.CMakeAnnotatorUtils.annotateCommand(CMakeAnnotatorUtils.java:187)
	at com.cmakeplugin.annotator.CMakeAnnotator.annotateCLion(CMakeAnnotator.java:74)
	at com.cmakeplugin.annotator.CMakeAnnotator.annotate(CMakeAnnotator.java:23)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.Pa

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: CLion 2022.3 Build: #CL-223.7571.171 November 28, 2022
Theme: GitHub Light
JRE: 17.0.5+1-b653.14, JetBrains s.r.o.
JVM: 17.0.5+1-b653.14, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.0.1 (x86_64)

=== Plugins ===
Custom plugins: [String Manipulation (9.6.1), Run Configuration as Action (1.4.5), Monokai Pro Theme (1.9), Monocai Color Theme (2.0.2c), Key Promoter X (2022.3), Gradianto (4.5), Ideolog (203.0.30.0), Window Layout Manager (1.4.0), CMake simple highlighter (223.2.1), OpenAPI Generator (4.3.1-p0), WebAssembly (1.4.223), Properties (223.7571.117), ToggleInclude (0.2.1), Xcode-Dark Theme (1.2.4), Solarized Theme (3.0.0), Lines Sorter (1.0.1), Atom One Theme (1.5.1), HOCON (2022.1.0), Nord (0.13.0), Xcode Theme (1.6.1), Material Theme UI Lite (19.0.0), .ignore (4.4.4), Protocol Buffers (223.7571.188), Ini (223.7571.188), ReStructuredText (223.7571.188), Foldable ProjectView (1.1.4), Vuesion Theme (1.9.2), Visual Studio Code Dark Plus Theme (2.6), Diff / Patch File Support (2.1.9), Wrap to Column (1.8.0), GitHub Theme (1.2.0), Cyan Light Theme (1.3), Translation (3.4.0)]
Disabled plugins:[TSLint (223.7571.171), NASM Assembly Language (0.5-beta.8), HTTP Client (223.7571.171), Node.js Remote Interpreter (223.7571.171), CMake Plus (223.2.1), Styled Components & Styled JSX (223.7571.171), Less (223.7571.171), cppcheck (1.6.2), SonarLint (7.2.0.56810), JavaScript Intention Power Pack (223.7571.171), HTML Tools (223.7571.171), ANTLR v4 (1.19.3-3), Subversion (223.7571.171), Perl (2022.2.2), Rust (0.4.183.5026-223), Perforce Helix Core (223.7571.171), Node.js (223.7571.171), Rainbow Brackets (2022.3.5), Sass (223.7571.171), GitToolBox (213.10.2), Mercurial (223.7571.171)]
```

**Comment by ArtsiomCh** [comment]
Hi @pzheltov ! Thanks for reporting! Please update plugin to the 223.3.0 where that issue is resolved.
