### ISSUE TITLE
[Exception][CLion 2022.3.1] java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: Ps...

### ISSUE THREAD

**Issue by PandaBoby** [ArtsiomCh/CMake#43]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: PsiErrorElement:应为 '(', ')' 或 <argument>, end: PsiErrorElement:应为 '(', ')' 或 <argument>, startContainingFile: FILE
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:65)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:81)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:69)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:52)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:45)
	at com.cmakeplugin.inspections.CommandSignatureObligatoryParamsNeededInspection$1.visitElement(CommandSignatureObligatoryParamsNeededInspection.java:31)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.cmake.psi.CMakeCommandImpl.accept(CMakeCommandImpl.java:25)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$9(InspectionRunner.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:332)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:338)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:301)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:301)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:284)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: CLion 2022.3.1 Build: #CL-223.8214.51 December 20, 2022
Theme: GitHub
JRE: 17.0.5+1-b653.23, JetBrains s.r.o.
JVM: 17.0.5+1-b653.23, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.1 (aarch64)

=== Plugins ===
Custom plugins: [Atom Material Icons (82.0.0), .ignore (4.4.4), CodeGlance3 (2.1.1-2021.1.3), JS Toolbox (1.10), Chinese (Simplified) Language Pack / 中文语言包 (223.228), Rainbow Brackets (2023.1.0), Redis Helper (beta-0.9.0), Rainbow Fart (1.3.6), GitToolBox (213.10.5), WebSocket Client (1.0.1), Gist Snippet (1.1.0), AceJump (3.8.10), Json Parser (1.4.1), Translation (3.4.1), Comments Highlighter (2.4.1), CMake Plus (223.6.1), Indent Rainbow (2.1.0), Ideolog (203.0.30.0), String Manipulation (9.6.1), Foldable ProjectView (1.1.4), CSV Editor (3.0.2-223), Protobuf Support (0.0.7), SonarLint (7.3.0.59206), CamelCase (3.0.12), A8Translate (1.8), cppcheck (1.6.2), Key Promoter X (2022.3), Tabnine AI Code Completion- JS Java Python TS Rust Go PHP & More (0.8.10), Workers integration (1.2.1), .env files support (2022.3), Markdown Editor (2.0.2), CMake simple highlighter (223.6.1), Material Theme UI Lite (20.0.0), Grep Console (12.15.211.6693.1)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Fixed in 223.6.2 (will be available within two business days on JetBrains approval)
@Maicosoft Thanks for reporting!!!
