### ISSUE TITLE
[Exception][Rider 2023.2] com.intellij.diagnostic.PluginException: Cannot create extension (class=com.cmakeplugin.CMa...

### ISSUE THREAD

**Issue by max4722** [ArtsiomCh/CMake#54]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.cmakeplugin.CMakeColorSettingsPage) [Plugin: artsiomch.cmake]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1067)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:69)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:30)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:474)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:265)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.kt:40)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.C(TextAttributesKeysStorage.kt:36)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.register(TextAttributesKeysStorage.kt:27)
	at com.jetbrains.rd.platform.daemon.TextAttributesRegistrationHost.getTextAttributesKey(TextAttributesRegistrationHost.kt:39)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.C(FrontendHighlighterRegistrationHost.kt:162)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.access$patchIdeaColorsScheme(FrontendHighlighterRegistrationHost.kt:34)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:79)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:78)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal$onWireReceived$2.invoke(RdSignal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal$onWireReceived$2.invoke(RdSignal.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:122)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:115)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:103)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:29)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.o

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2023.2 Build: #RD-232.8660.212 July 31, 2023
Theme: Rider Night
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Toml (232.8660.88), Material Theme UI (8.10.0), Json Parser (1.7), Go Template (232.8660.88), Rider Xamarin Android Support (232.8660.212), NSubstituteComplete (1.10.0), Python Community Edition (232.8660.185), MoqComplete (2023.2.0.1), Entity Framework Core UI (232.0.0-rc1), CMake simple highlighter (232.1.0), AWS Toolkit (1.75-232), Image Diff (1.11.0), Structured Logging (2023.2.0.305), Dart (232.8660.129), Heap Allocations Viewer (2023.2.0), Kubernetes (232.8660.158), AWS CloudFormation (232.8660.88), Makefile Language (232.8660.88), Azure DevOps (1.162.2), Statistic (4.2.7), CMD Support (1.0.5), Swagger (1.2.0), String Manipulation (9.10.0), Apache config (.htaccess) (232.8660.205), Grazie Lite (232.8660.88), Perl (2023.2), Ansible (0.92), CamelCase (3.0.12), Rider Keymap (201.6251.22), PowerShell (2.0.10), Rust (0.4.200.5421-232), CognitiveComplexity (2023.2.0), Batch Scripts Support (1.0.13), AI Assistant (232.9520), GitToolBox (500.0.13+213), .ignore (4.5.1), YAML/Ansible support (0.11.2), Ideolog (222.1.0.0)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 232.1.1 (should be alliable in marketplace within 2 business days)
