### ISSUE TITLE
[Exception][Rider 2023.2] com.intellij.diagnostic.PluginException: Cannot create extension (class=com.cmakeplugin.CMa...

### ISSUE THREAD

**Issue by Lurenlzm** [ArtsiomCh/CMake#56]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.cmakeplugin.CMakeColorSettingsPage) [Plugin: artsiomch.cmake]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1067)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:69)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:30)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:474)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:265)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.kt:40)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:33)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:539)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:531)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:515)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:377)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:307)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:148)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:157)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:110)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:119)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.getConfigurableGroups(ShowSettingsUtilImpl.kt:48)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.kt)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:538)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:261)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$3(ActionPopupStep.java:238)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1636)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:173)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:210)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:176)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:169)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:163)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1634)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
	at com.intellij.ui.popup.list

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2023.2 Build: #RD-232.8660.212 August 1, 2023
Theme: Rider Day
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [CMake simple highlighter (232.1.0), One Dark theme (5.8.0)]
Disabled plugins:[Rider C++ IntelliLang (232.8660.212), Unity Support (2023.2.0.151), FTP/SFTP/WebDAV Connectivity (232.8660.212), Dynamic Program Analysis (232.8660.212), YourKit Profiler for IDE Performance Testing (232.8660.212), Terminal for Gateway (232.8660.212), Mercurial (232.8660.212), File Watchers (232.8660.212), OpenAPI Specifications (232.8660.212), XPathView + XSLT (232.8660.212), Machine Learning in Search Everywhere (232.8660.212), Vagrant (232.8660.212), Support for ASP.NET and Razor (232.8660.212), Time Tracking (232.8660.212), Subversion (232.8660.212), Pug (ex-Jade) (232.8660.212), HTML Tools (232.8660.212), Dev Containers (232.8660.212), Live Edit (232.8660.212), Angular and AngularJS (232.8660.212), SSH Remote Run (232.8660.212), Karma (232.8660.212), Perforce Helix Core (232.8660.212), Docker (232.8660.212), Node.js (232.8660.212), Vue.js (232.8660.212), Less (232.8660.212), GitHub Copilot (1.2.18.2908), F# Support (2023.2.153), JavaScript Intention Power Pack (232.8660.212), Support for publishing to custom servers (232.8660.212), Refactor-X (232.8660.212), Polymer & Web Components (232.8660.212), ForTea (2023.2.151), Remote Development Gateway (232.8660.212), Task Management (232.8660.212), Endpoints (232.8660.212), IntelliLang (232.8660.212), Machine Learning Code Completion (232.8660.212), dotCover (232.8660.212), Webpack (232.8660.212), Styled Components & Styled JSX (232.8660.212), dotTrace and dotMemory (232.8660.212), Qodana (232.8660.212), Performance Testing (232.8660.212), Code With Me (232.8660.212), TextMate Bundles (232.8660.212), EditorConfig (232.8660.212), TSLint (232.8660.212), JavaScript Debugger (232.8660.212), Handlebars/Mustache (232.8660.212), Space (232.8660.212), W3C Validators (232.8660.212), Node.js Remote Interpreter (232.8660.212), dotCommon (232.8660.212), GitHub (232.8660.212), Rider Diagrams (232.8660.212), Diagrams (232.8660.212), Sass (232.8660.212)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 232.1.1 (should be alliable in marketplace within 2 business days)
