### ISSUE TITLE
Loading error in Clion EAP(CL-193.3793.19)  with 193.0.1.EAP-based-on-192.4.2

### ISSUE THREAD

**Issue by csitarichie** [ArtsiomCh/CMake#7]
I have tried to install the latest beta version of the plugin in the Clion EAP on Linux.
I have downloaded the plugin directly from JetBrains plugin store and used install from disk.
(the plugin not visible in the normal plugin market place in EAP Clion BTW ).

When restarting Clion after install the following error message comes:
```
plugin 'artsiomch.cmake.plus' failed to initialize and will be disabled.  Please restart CLion.

java.lang.RuntimeException: java.lang.IllegalStateException: Native library for Attach API not available in this JRE (probably no JDK on classpath)
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:92)
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:70)
    at com.cmakeplugin.agent.CMakeInstrumentationUtils.patchJBclasses(CMakeInstrumentationUtils.java:69)
    at com.cmakeplugin.CMakePlusComponent.initComponent(CMakePlusComponent.java:42)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:42)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$3(ApplicationImpl.java:335)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:335)
    at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:199)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:396)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalStateException: Native library for Attach API not available in this JRE (probably no JDK on classpath)
    at org.avaje.agentloader.load.EmbeddedHelp.getVirtualMachineImplementationFromEmbeddedOnes(EmbeddedHelp.java:81)
    at org.avaje.agentloader.load.DirectLoader.loadAgent(DirectLoader.java:41)
    at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:86)
    ... 31 more
Caused by: java.lang.UnsatisfiedLinkError: 'boolean sun.tools.attach.LinuxVirtualMachine.isLinuxThreads()'
    at sun.tools.attach.LinuxVirtualMachine.isLinuxThreads(Native Method)
    at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:337)
    at org.avaje.agentloader.load.EmbeddedHelp.getVirtualMachineImplementationFromEmbeddedOnes(EmbeddedHelp.java:67)
    ... 33 more
 ```

**Comment by ArtsiomCh** [comment]
@csitarichie Try this one please: https://github.com/ArtsiomCh/CMake/releases/download/193.0.2/CMake-plus-193.0.2.EAP-based-on-192.4.2.jar

**Comment by csitarichie** [comment]
@ArtsiomCh I can confirm that the 193.0.2 version is working on CLion 193.3793.19 EAP build on Ubuntu Linux 19.10 and Mac OS Catalina. 

It is just weird that when JetBrains ToolBox updates Clion to EAP it disables both Cmake Simple Highlighter and CMake plus plugins even there is a beta available from you in the plugin market place. 

I think it would make sense to have a word on that with JetBrains. :).

Never the less after installing it by hand and using new version from above everything works as before in CLion EAP. 

Thanks for the quick fix.
